<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="NRES 710" />


<title>Analysis of Categorical Data</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NRES 710</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Syllabus</a>
</li>
<li>
  <a href="schedule.html">Schedule</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lecture_1.html">Syllabus and the Purpose of Statistics</a>
    </li>
    <li>
      <a href="lecture_2.html">P-value Discussion and Intro to R</a>
    </li>
    <li>
      <a href="lecture_3.html">Sampling Uncertainty</a>
    </li>
    <li>
      <a href="lecture_4.html">Linear Regression</a>
    </li>
    <li>
      <a href="lecture_5.html">Linear Regression - results</a>
    </li>
    <li>
      <a href="lecture_6.html">Linear Regression - assumptions</a>
    </li>
    <li>
      <a href="lecture_7.html">Linear Regression - predictions</a>
    </li>
    <li>
      <a href="lecture_8.html">Analysis of Categorical Data - 2 groups</a>
    </li>
    <li>
      <a href="lecture_9.html">Analysis of Categorical Data - &gt;2 groups</a>
    </li>
    <li>
      <a href="lecture_10.html">Analysis of Categorical Data - posthoc tests</a>
    </li>
    <li>
      <a href="lecture_11.html">Analysis with Continuous or Categorical X?</a>
    </li>
    <li>
      <a href="LECTURE8.html">GLM</a>
    </li>
    <li>
      <a href="LECTURE9.html">GLMM</a>
    </li>
    <li>
      <a href="LECTURE10.html">Machine Learning</a>
    </li>
    <li>
      <a href="GIT_tutorial.html">Intro to GIT</a>
    </li>
    <li>
      <a href="LECTURE11.html">Next steps</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="exercise_1.html">Exercise 1 - Data Summary Functions</a>
    </li>
    <li>
      <a href="exercise_2.html">Exercise 2 - Linear Regression</a>
    </li>
    <li>
      <a href="exercise_3.html">Exercise 3 - Linear Regression (cont.)</a>
    </li>
    <li>
      <a href="exercise_4.html">Exercise 4 - Analysis of Categorical Data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    More Resources
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Links.html">Links</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Analysis of Categorical Data</h1>
<h4 class="author">NRES 710</h4>
<h4 class="date">Last compiled: 2024-08-05</h4>

</div>


<div id="summary" class="section level2">
<h2>Summary</h2>
<p>Up to this point, we have been operating under the idea that we have
been examing the relationship between a <strong>continuous Y
variable</strong> and a <strong>continuous X variable</strong>.</p>
<p>What if we no longer have a continuous X-variable, but instead have a
<strong>categorical X-variable</strong>?</p>
<p>Let’s assume that X-variable is binomial (two categories):</p>
<p><strong>Continuous Y, Categorical X (binomial)</strong></p>
<p><strong>Q:</strong> How would we typically analyze data with a
categorical X and a continuous, normally-distributed Y?</p>
<p><strong>t-Test!</strong> Named after the ‘Student t
distribution’.</p>
<p><br></p>
</div>
<div id="t-tests" class="section level2">
<h2>t-Tests</h2>
<p>For example, let’s say we are interested in testing for body size
differences between two sexes of <strong>elephant seal</strong>
(<em>Mirounga leonina</em>).</p>
<p><img src="pic_seal.png" style="width:50.0%" /></p>
<p>Photo: Luke Verburgt</p>
<p><strong><span class="math inline">\(X_1\)</span> = male, <span
class="math inline">\(X_2\)</span> = female, <span
class="math inline">\(Y\)</span> = length</strong></p>
<p>Our data might look like this:</p>
<p><img src="lecture_8_files/figure-html/size-1.png" width="432" /></p>
<p>Both the female and male data are normally distributed. I’m putting a
slight ‘jitter’ on these points, so they can be visualized easier by the
naked eye.</p>
<p>We want to know: how much larger are males than females? Or, what is
the difference between the mean of females and males? We can visualize
this with a horizontal line in the middle of each point cloud, and an
arrow between the two means.</p>
<p>Our scientific effort might focus on testing the null hypothesis:</p>
<p><strong><span class="math inline">\(H_0\)</span>: no difference
between groups</strong></p>
<ul>
<li>Or, <strong><span class="math inline">\(\mu_{females} =
\mu_{males}\)</span></strong></li>
<li>Or, <strong><span class="math inline">\(\mu_{females} -
\mu_{males}\)</span> = 0</strong></li>
</ul>
<p>These are all the same, and are core to our science-drive hypothesis
that we want to test.</p>
<p>From a statistical perspective, we are interested in knowing whether
males are significantly larger than females, and measuring that effect
(if any).</p>
<p>Let’s assume that we know truth for this graph:</p>
<ul>
<li>Average mass of males is 250 kg</li>
<li>Average mass of females is 200 kg</li>
<li><span class="math inline">\(\sigma\)</span> = 20 kg</li>
</ul>
<p>The truth is that males are larger than females.</p>
<div id="simple-t-test-in-r" class="section level3">
<h3>Simple t-test in R</h3>
<p>Let’s make these data in R, and run a t-test:</p>
<pre class="r"><code>### Code for simulating data to be analyzed body size data for two sexes

# Set the seed for reproducibility
set.seed(123)

# Simulate the binomial X-variable (sex)
n &lt;- 40
x &lt;- c(rep(&quot;Female&quot;, n/2), rep(&quot;Male&quot;, n/2))
x &lt;- factor(x)

# Simulate continuous y-variable data
y &lt;- ifelse(x == &quot;Female&quot;,
            rnorm(n/2, mean = 200, sd = 20), #females
            rnorm(n/2, mean = 250, sd = 20)) #males

# Create dataframe
datum &lt;- data.frame(Sex = x, Size = y)

# Examine the data
head(datum)</code></pre>
<pre><code>##      Sex     Size
## 1 Female 188.7905
## 2 Female 195.3965
## 3 Female 231.1742
## 4 Female 201.4102
## 5 Female 202.5858
## 6 Female 234.3013</code></pre>
<pre class="r"><code>tail(datum)</code></pre>
<pre><code>##     Sex     Size
## 35 Male 266.4316
## 36 Male 263.7728
## 37 Male 261.0784
## 38 Male 248.7618
## 39 Male 243.8807
## 40 Male 242.3906</code></pre>
<pre class="r"><code># Plot the data to examine it!
plot(Size ~ Sex, data=datum)</code></pre>
<p><img src="lecture_8_files/figure-html/size-2-1.png" width="432" /></p>
<pre class="r"><code># Box and whiskers plot!
# Bold black line = median
# Edges of box: 75% and 25% quartiles
# Bars: 95% limits
# Points: outliers, or 5% of data outside of the 95% intervals

# Analyze this using the &#39;t.test()&#39; function in R:
help(t.test)
results &lt;- t.test(Size ~ Sex, data = datum)

# Examine the summary
summary(results)</code></pre>
<pre><code>##             Length Class  Mode     
## statistic   1      -none- numeric  
## parameter   1      -none- numeric  
## p.value     1      -none- numeric  
## conf.int    2      -none- numeric  
## estimate    2      -none- numeric  
## null.value  1      -none- numeric  
## stderr      1      -none- numeric  
## alternative 1      -none- character
## method      1      -none- character
## data.name   1      -none- character</code></pre>
<pre class="r"><code># Some functions in R don&#39;t have summary functions for them because they are so simple!

# Just ask for the object
results</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Size by Sex
## t = -8.0694, df = 37.082, p-value = 1.104e-09
## alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
## 95 percent confidence interval:
##  -57.72764 -34.55712
## sample estimates:
## mean in group Female   mean in group Male 
##             202.8325             248.9749</code></pre>
<p>All the results come from the object itself!</p>
<ul>
<li>t-statistic</li>
<li>degrees of freedom</li>
<li>p-value – testing the null hypothesis that there is no difference in
the means between the two groups</li>
<li>95% confidence intervals – on the difference between the two
groups</li>
<li>average size of female group</li>
<li>average size of male group</li>
</ul>
<p><strong>Q:</strong> What is the one thing it doesn’t give us that we
might want to see??</p>
<p>It does not provide an <strong>estimate</strong> of the size
difference between two groups!! This is not helpful (and somewhat
silly)!</p>
<p>We can calculate it by doing some math… subtract the smaller group
from the larger group:</p>
<pre class="r"><code>251.2 - 198.9</code></pre>
<pre><code>## [1] 52.3</code></pre>
<p>This is how much larger the males are than females.</p>
<p>The confidence interval would be:</p>
<pre class="r"><code>(64.44 - 40.14)/2</code></pre>
<pre><code>## [1] 12.15</code></pre>
<p><strong>Q:</strong> Why is the 95% confidence interval that R
provided negative?</p>
<p>R calculated this effect as doing females minus males, whereas I
calculated it as males minus females. We just need to be savvy to make
sure we think about the outputs and ensure that everything makes sense.
Use common sense.</p>
<p><strong>Questions?</strong></p>
</div>
</div>
<div id="t-tests-are-just-a-regression" class="section level2">
<h2>t-tests are just a regression</h2>
<p>One thing that always confused me about learning statistics as an
undergraduate and graduate student was that all of the usual analyses
(regression, t-test, ANOVA, ANCOVA, etc.) are all taught as ‘different
tests’. It creates many more boxes and relationships that you have to
memorize – different things to categorize in your brain as different and
thus requires more effect to memorize.</p>
<p>Here’s a little secret… t-tests are just a
<strong>regression</strong>! And can be analyzed as such with
‘lm()’!</p>
<p><strong>Q:</strong> What’s our linear model again??</p>
<p><strong><span class="math inline">\(Y = \beta_0 + \beta_1 X_1 +
\epsilon \sim N(0, \sigma)\)</span></strong></p>
<p>We can use the <strong>linear model</strong> to analyze the elephant
seal size data!</p>
<p><strong><span class="math inline">\(Size = \beta_0 + \beta_1 Sex +
\epsilon \sim N(0, \sigma)\)</span></strong></p>
<p>Questions you might ask yourself:</p>
<ul>
<li>Why teach this as a whole-new test, when it’s the same mathematical
formula we have looked at all along?</li>
<li>And, since sex is not a number, how would this work?</li>
</ul>
<p>It works through the magical process of
<strong>‘dummy-coding’</strong>!</p>
<p><strong>Dummy-coding – a process to convert categories to 1s and
0s.</strong> For example:</p>
<p><strong>Sex:</strong> <strong>Male:</strong></p>
<p>Male 1<br />
Male 1<br />
Female 0<br />
Female 0</p>
<p>Now, we can replace our <strong>sex</strong> variable with
<strong>male</strong>:</p>
<p><strong><span class="math inline">\(Size = \beta_0 + \beta_1 Male +
\epsilon \sim N(0, \sigma)\)</span></strong></p>
<p>Let’s examine how this works mathematically. Anytime a sample is a
male, it gives us a 1 here. Anytime a sample is female, it gives us a 0.
Using this information, we can simplify this formula and see how it
gives us the answer for both sexes.</p>
<ul>
<li><span class="math inline">\(Size_{females} = \beta_0 + \epsilon \sim
N(0, \sigma)\)</span></li>
<li><span class="math inline">\(Size_{males} = \beta_0 + \beta_1 +
\epsilon \sim N(0, \sigma)\)</span></li>
</ul>
<p><strong>Q:</strong> Everyone follow what we just did here?</p>
<p><strong>Q:</strong> Looking at these equations, what is the meaning
of <span class="math inline">\(\beta_0\)</span>?</p>
<ul>
<li><strong>Average size of females</strong></li>
<li><strong>Or, more generically, the average Y of the reference
group</strong> – samples that were assigned 0.</li>
</ul>
<p><strong>Q:</strong> Looking at these equations, what is the meaning
of <span class="math inline">\(\beta_1\)</span>?</p>
<ul>
<li><strong>Difference between groups</strong> – this is what we want to
know! The thing that the null hypothesis is testing – whether this
effect is different than zero or not. This is the thing the ‘t.test()’
function didn’t even measure for us… (what a shame!)</li>
</ul>
<p>Let’s go back to our original graph.</p>
<pre class="r"><code># Plot
stripchart(Size ~ Sex, data = datum, vertical = TRUE, method = &quot;jitter&quot;, 
           pch = 19, xlab = &quot;Sex&quot;, ylab = &quot;Body size (cm)&quot;)</code></pre>
<p><img src="lecture_8_files/figure-html/size-5-1.png" width="432" /></p>
<p><strong>Q:</strong> how might we visualize <span
class="math inline">\(\beta_0\)</span> and <span
class="math inline">\(\beta_1\)</span> on this graph?</p>
<p>If we remember that female is 0, then <span
class="math inline">\(\beta_0\)</span> is the y-intercept, or the body
size when y=0.</p>
<p>And then <span class="math inline">\(\beta_1\)</span> is the
difference between these two groups.</p>
<p><strong>Q:</strong> How do we calculate slope again? Rise over
run.</p>
<p>Since males are 1, then the ‘run’ is from 0 to 1 – which equals 1.
The rise is <span class="math inline">\(\beta_1\)</span> divided by 1,
which equals <span class="math inline">\(\beta_1\)</span>.</p>
<p>So <span class="math inline">\(\beta_1\)</span> is still the slope,
but it’s also more simply just the difference between the groups.</p>
<p>So: why think about this as a t-test? Perhaps it would be easier to
use the linear model that we have studied for three weeks, and gotten to
know pretty well – and instead say that our X-variable is categorical,
rather than continuous.</p>
<p>Let’s see what this looks like by trying this again in R.</p>
</div>
<div id="analysis-of-categorical-data-w-lm" class="section level2">
<h2>Analysis of categorical data w/ lm()</h2>
<pre class="r"><code>### Code for simulating data to be analyzed body size data for two sexes

# Recall our &#39;datum&#39; object
head(datum)</code></pre>
<pre><code>##      Sex     Size
## 1 Female 188.7905
## 2 Female 195.3965
## 3 Female 231.1742
## 4 Female 201.4102
## 5 Female 202.5858
## 6 Female 234.3013</code></pre>
<pre class="r"><code>tail(datum)</code></pre>
<pre><code>##     Sex     Size
## 35 Male 266.4316
## 36 Male 263.7728
## 37 Male 261.0784
## 38 Male 248.7618
## 39 Male 243.8807
## 40 Male 242.3906</code></pre>
<pre class="r"><code># We need to &#39;dummy-code&#39; our Sex variable, e.g., as &#39;Male&#39;
Male &lt;- c(rep(0, n/2), rep(1, n/2))

# Add &#39;Male&#39; to the dataframe
datum &lt;- cbind(datum, Male)

# Plot the data!
plot(Size ~ Male, data = datum)</code></pre>
<p><img src="lecture_8_files/figure-html/size-6-1.png" width="432" /></p>
<p>Note: previously R made the X-axis as a categorical (female
vs. male), but now it’s continuous… R automatically makes graphs
depending on it’s default interpretation of the data. It reads
characters/letters as ‘categorical’ and numbers and continuous
variables. Since we swapped this to be dummy-coded with 1s and 0s, it
automatically scaled the X-axis as continuous!</p>
<p>Let’s now try to run our t-test using ‘lm()’:</p>
<pre class="r"><code># Examine the old t-test results
results</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Size by Sex
## t = -8.0694, df = 37.082, p-value = 1.104e-09
## alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
## 95 percent confidence interval:
##  -57.72764 -34.55712
## sample estimates:
## mean in group Female   mean in group Male 
##             202.8325             248.9749</code></pre>
<pre class="r"><code>248.9749 - 202.8325 # effect of being male</code></pre>
<pre><code>## [1] 46.1424</code></pre>
<pre class="r"><code># Use lm() to run regression with dummy-coded X-data
results2 &lt;- lm(Size ~ Male, data = datum)
summary(results2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Male, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.165 -12.604  -0.433  12.777  32.906 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  202.832      4.043  50.164  &lt; 2e-16 ***
## Male          46.142      5.718   8.069 9.24e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.08 on 38 degrees of freedom
## Multiple R-squared:  0.6315, Adjusted R-squared:  0.6218 
## F-statistic: 65.12 on 1 and 38 DF,  p-value: 9.239e-10</code></pre>
<p><strong>Q:</strong> What do we see??</p>
<ul>
<li>Average size of females: 202.8 from t-test, compared to intercept
202.8 from regression</li>
<li>Effect of being male: 46.1 from t-test, 46.1 from regression</li>
</ul>
<p>The numbers are the same!</p>
<p>Turns out that when you run ‘t.test()’, it does dummy-coded behind
the scenes, and then just runs a ‘lm()’.</p>
<pre class="r"><code># Confidence intervals
confint(results2)</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 194.64712 211.01783
## Male         34.56654  57.71822</code></pre>
<p>Confidence intervals also ~match up between t-test and lm
results.</p>
<p>What if we run a regression but with a categorical X-variable…?</p>
<pre class="r"><code># Regression with a categorical variable
results3 &lt;- lm(Size ~ Sex, data = datum)
summary(results3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Sex, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.165 -12.604  -0.433  12.777  32.906 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  202.832      4.043  50.164  &lt; 2e-16 ***
## SexMale       46.142      5.718   8.069 9.24e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.08 on 38 degrees of freedom
## Multiple R-squared:  0.6315, Adjusted R-squared:  0.6218 
## F-statistic: 65.12 on 1 and 38 DF,  p-value: 9.239e-10</code></pre>
<p>This works also! Because R will automatically turn that categorical
X-variable into a dummy-coded continuous variable. In this case, it
became 1 for ‘SexMale’ and 0 for ‘SexFemale’. It chose ‘Female’ as the
reference group, and male becomes the group females are being compared
to.</p>
<p><strong>Q:</strong> Why did it choose ‘Female’ as the reference?
Alphabetical order.</p>
<p>So, you don’t even have to do the dummy-coding – R can do that for
you! (Although I still like to, to be sure I know what’s going on.)</p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>What this means is: we don’t actually have to memorize “Do I do a
t-test here, or a regression here, for these data…?” It doesn’t
matter!</p>
<p>The lightbulb turned on for me with statistics when I realized that
we don’t have to remember all the different situations for which you
would run a t-test, ANOVA, regression, ANCOVA, etc…</p>
<p>Instead, <strong><em>every analysis can be done with some form of a
linear model</em></strong>.</p>
<p>For the rest of the semester, we will continue to revisit our
tried-and-true formula for the linear model:</p>
<p><strong><span class="math inline">\(Y = \beta_0 + \beta_1 X_1 +
\epsilon \sim N(0, \sigma)\)</span></strong></p>
<p>And then we will tweak it just a little bit, week by week, until we
use this basic formula for the entire class. It will be a little more
complicated each week, but it will be easier to understand because we
will build on it slowly, carefully, and hopefully in a logical way!</p>
<p>We will learn how to tweak this formula to analyze our data as the
data become more complicated.</p>
<p><strong>Note:</strong> We can’t use our same canned statement for
reporting results like we used for linear regression. Next class we will
learn how to report our results when X-variable is categorical. And then
we will extend the formula to accommodate situations for when we have
more than two groups. And then we will keep moving on from there!</p>
<p><a href="lecture_9.html">–go to next lecture–</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
