<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="NRES 710" />


<title>Analysis of Categorical Data (cont.)</title>

<script src="site_libs/header-attrs-2.27/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NRES 710</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Syllabus</a>
</li>
<li>
  <a href="schedule.html">Schedule</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lectures
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lecture_1.html">Syllabus and the Purpose of Statistics</a>
    </li>
    <li>
      <a href="lecture_2.html">P-value Discussion and Intro to R</a>
    </li>
    <li>
      <a href="lecture_3.html">Sampling Uncertainty</a>
    </li>
    <li>
      <a href="lecture_4.html">Linear Regression</a>
    </li>
    <li>
      <a href="lecture_5.html">Linear Regression - results</a>
    </li>
    <li>
      <a href="lecture_6.html">Linear Regression - assumptions</a>
    </li>
    <li>
      <a href="lecture_7.html">Linear Regression - predictions</a>
    </li>
    <li>
      <a href="lecture_8.html">Analysis of Categorical Data - 2 groups</a>
    </li>
    <li>
      <a href="lecture_9.html">Analysis of Categorical Data - &gt;2 groups</a>
    </li>
    <li>
      <a href="lecture_10.html">Analysis of Categorical Data - posthoc tests</a>
    </li>
    <li>
      <a href="lecture_11.html">Analysis with Continuous or Categorical X?</a>
    </li>
    <li>
      <a href="lecture_12.html">Multi-variable Modeling</a>
    </li>
    <li>
      <a href="LECTURE8.html">GLM</a>
    </li>
    <li>
      <a href="LECTURE9.html">GLMM</a>
    </li>
    <li>
      <a href="GIT_tutorial.html">Intro to GIT</a>
    </li>
    <li>
      <a href="LECTURE11.html">Next steps</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="exercise_1.html">Exercise 1 - Data Summary Functions</a>
    </li>
    <li>
      <a href="exercise_2.html">Exercise 2 - Linear Regression</a>
    </li>
    <li>
      <a href="exercise_3.html">Exercise 3 - Linear Regression (cont.)</a>
    </li>
    <li>
      <a href="exercise_4.html">Exercise 4 - Analysis of Categorical Data</a>
    </li>
    <li>
      <a href="exercise_5.html">Exercise 5 - Analysis of Continuous and Categorical Data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    More Resources
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Links.html">Links</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Analysis of Categorical Data (cont.)</h1>
<h4 class="author">NRES 710</h4>
<h4 class="date">Last compiled: 2024-08-06</h4>

</div>


<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
  MathJax.Hub.Insert(MathJax.InputJax.TeX.Definitions.macros,{
    cancel: ["Extension","cancel"],
    bcancel: ["Extension","cancel"],
    xcancel: ["Extension","cancel"],
    cancelto: ["Extension","cancel"]
  });
});
</script>
<div id="summary" class="section level2">
<h2>Summary</h2>
<p>Last class we discussed how to analyze data when we have a
categorical X-variable data.</p>
<p>Traditionally, this is called a <em>t-test</em> – but I am going to
avoid calling it that going forward. Instead, we are always going to be
using the <strong>linear model</strong> in this class, which is more
<em>parsimonious</em> (simple) and will create continuity with the
approach we are going to take toward understanding statistics in this
class</p>
<p>Today we will discuss how to <strong>present results</strong> from
analysis of categorical data. We have a ‘canned’ sentence for presenting
results when we have two continuous variables, but we need a slightly
different approach for when we have categorical X-data.</p>
<p>The good news is that our X-variable data can only be continuous or
categorical. So once we learn this second approach, we will only have to
know these <strong>two approaches</strong>. We can use them repeatedly
during our various analytical activities, perhaps with slight
modifications.</p>
</div>
<div id="presenting-results" class="section level2">
<h2>Presenting Results</h2>
<p>With continuous X data, we start out by saying: “For each 1 unit
increase in X, we observed a unit change in Y.” There is no such thing
as a unit change in X when we have a categorical X variable, so we will
drop that. Instead, we will say something like:</p>
<p>**“We found that [group 1] was [<span
class="math inline">\(\beta_1\)</span>] [Y-units] ([+/-CI]; 95% CI)
[descriptor word to indicate direction] than [group 2] (p =
[p-value]).”</p>
<ul>
<li>*if p &gt; 0.05, then add: “; however, our results were not
statistically significant.”</li>
</ul>
<div id="example" class="section level3">
<h3>Example</h3>
<p>Let’s take a peak in R at the elephant <a
href="lecture_8_seal_data.csv">seal body size data</a> from last class.
We will analyze it using ‘lm()’ with a categorical X-variable:</p>
<pre class="r"><code># Load the data
datum &lt;- read.csv(&quot;lecture_8_seal_data.csv&quot;)

# Examine it
head(datum)</code></pre>
<pre><code>##   X    Sex     Size Male
## 1 1 Female 188.7905    0
## 2 2 Female 195.3965    0
## 3 3 Female 231.1742    0
## 4 4 Female 201.4102    0
## 5 5 Female 202.5858    0
## 6 6 Female 234.3013    0</code></pre>
<pre class="r"><code>tail(datum)</code></pre>
<pre><code>##     X  Sex     Size Male
## 35 35 Male 266.4316    1
## 36 36 Male 263.7728    1
## 37 37 Male 261.0784    1
## 38 38 Male 248.7618    1
## 39 39 Male 243.8807    1
## 40 40 Male 242.3906    1</code></pre>
<pre class="r"><code># Examine structure of data
str(datum)</code></pre>
<pre><code>## &#39;data.frame&#39;:    40 obs. of  4 variables:
##  $ X   : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Sex : chr  &quot;Female&quot; &quot;Female&quot; &quot;Female&quot; &quot;Female&quot; ...
##  $ Size: num  189 195 231 201 203 ...
##  $ Male: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
<pre class="r"><code># Force &#39;Sex&#39; to be a factor
datum$Sex &lt;- factor(datum$Sex)

# Scatterplot
plot(Size ~ Sex, data = datum)</code></pre>
<p><img src="lecture_9_files/figure-html/seals-1.png" width="432" /></p>
<pre class="r"><code># Fit a linear model
results &lt;- lm(Size ~ Sex, data = datum)
summary(results)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Sex, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.165 -12.604  -0.433  12.777  32.906 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  202.832      4.043  50.164  &lt; 2e-16 ***
## SexMale       46.142      5.718   8.069 9.24e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.08 on 38 degrees of freedom
## Multiple R-squared:  0.6315, Adjusted R-squared:  0.6218 
## F-statistic: 65.12 on 1 and 38 DF,  p-value: 9.239e-10</code></pre>
<p>Let’s talk about this a bit to make sure we are all on the same
page.</p>
<p>The analysis output from linear regression with <strong>categorical
X-data</strong> is the same output that we got when we ran linear
regression using <strong>two continuous variables</strong>.</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> – the Y-intercept;
previously this was the value when Y = 0; now it is slightly different,
it is still the Y-value when X = 0, but we can more technically define
this as the average Y-value for the ‘reference group’.
<ul>
<li>We get to choose what the reference group is. By default, R chose
‘female’ as the reference group, and we can see that because ‘SexMale’
was the <span class="math inline">\(\beta_1\)</span> effect.</li>
</ul></li>
<li><span class="math inline">\(\beta_1\)</span> – the difference in
size between males and females. The <strong>p-value</strong> is testing
the null hypothesis that there is no difference in size between males
and females.</li>
<li>Residual standard error – noise around the average</li>
<li>Everything else is still the same</li>
</ul>
<p>We can now use this output to populate the our ‘presenting
resultings’ sentence. We will need the +/- 95% CI:</p>
<pre class="r"><code># Confidence intervals
confint(results)</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 194.64712 211.01783
## SexMale      34.56654  57.71822</code></pre>
<pre class="r"><code># Calculate confidence intervals
57.7 - 46.1</code></pre>
<pre><code>## [1] 11.6</code></pre>
<pre class="r"><code># simple way: upper limit minus mean
confint(results)[&quot;SexMale&quot;, 2] - results$coefficients[&quot;SexMale&quot;]</code></pre>
<pre><code>##  SexMale 
## 11.57584</code></pre>
<pre class="r"><code># extracting estimates from objects to do math</code></pre>
<p><strong>“We found that males were 46.1 kg (+/-11.6; +/-95% CI)
heavier than females (p = 9.24e-10).”</strong></p>
<p>You could also be more descriptive and perhaps say: “had 46.1 kg (…)
greater mass than females”. It’s nice to be descriptive – but also good
to keep things concise.</p>
<p>What if you wanted to put females first? That’s fine – just swap
things around, word smith it a bit, and put females first: “We found
that females had 46.1 kg (…) less mass than males”.</p>
<p>If you give R categorical data, R will automatically create the
‘reference’ group using the alphabetical order of the groups. For
example, if you gave R data with two experimental treatments in the
X-variable, “control” and “burned”, it will automatically make “burned”
the reference group – but you might want to change that to visualize the
‘effect’ of burn treatment compared to control, untreated areas.</p>
<p><strong>Takehome message:</strong> Running a t-test is the same as
running a regression, but with a categorical X-variable – but it doesn’t
matter with coding in R. The only difference is you have to understand
that you have a categorical X-variable, and write a slightly different
sentence.</p>
</div>
<div id="changing-the-reference-group" class="section level3">
<h3>Changing the reference group</h3>
<p>We can change what the reference group is in R using the ‘factor()’
function. For example, using our seal data:</p>
<pre class="r"><code># Examine the categorical data
str(datum$Sex)</code></pre>
<pre><code>##  Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<pre class="r"><code># The &#39;levels&#39; are the groups in the variable, and they are ordered alphabetically by default.

# Re-order the levels
datum$Sex &lt;- factor(datum$Sex, levels = c(&quot;Male&quot;, &quot;Female&quot;)) # switch the order

# Re-run model
results2 &lt;- lm(Size ~ Sex, data = datum)
summary(results2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Sex, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.165 -12.604  -0.433  12.777  32.906 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  248.975      4.043  61.576  &lt; 2e-16 ***
## SexFemale    -46.142      5.718  -8.069 9.24e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.08 on 38 degrees of freedom
## Multiple R-squared:  0.6315, Adjusted R-squared:  0.6218 
## F-statistic: 65.12 on 1 and 38 DF,  p-value: 9.239e-10</code></pre>
<p>Now ‘SexFemale’ is the <span class="math inline">\(\beta_1\)</span>
effect.</p>
</div>
</div>
<div id="multiple-groups" class="section level2">
<h2>Multiple groups</h2>
<p>Let’s extend this model a little bit. Previously we had considered a
situation where we had a ‘binomial’ X-variable (<em>bi-</em> and
<em>nomial</em> = <em>two</em> <em>names</em> = a categorical variable
with two categories). Let’s now consider a situation where we have a
multinomial (<em>multi-</em> = more than two) X-variable with more than
two categories within it.</p>
<p><strong>Continuous Y; Multinomial X</strong></p>
<ul>
<li><strong>X-variable: Group 1 - Juveniles, Group 2 - Subadults, Group
3 - Adults</strong></li>
<li><strong>Y-variable: body size (mass)</strong></li>
</ul>
<p>The first thing I want to show you is how this works in the general
linear modeling framework. Up to this point, we have used our trusty
equation for the linear model as:</p>
<p><strong><span class="math inline">\(Y = \beta_0 + \beta_1 X_1 +
\epsilon \sim N(0, \sigma)\)</span></strong></p>
<p>We previously introduced the concept of ‘dummy coding’, which will be
particularly useful for us to explain how to extend our simple linear
model to accommodate multiple groups.</p>
<p>We will take our categorical X-variable and ‘dummy code’ it by
creating a <strong>column for each category</strong> that describes
whether each observation in our data is <strong>within that category (1)
or not (0)</strong>. For example:</p>
<pre><code>##        Age Juvenile Subadult Adult
## 1 Juvenile        1        0     0
## 2 Juvenile        1        0     0
## 3 Juvenile        1        0     0
## 4 Subadult        0        1     0
## 5 Subadult        0        1     0
## 6 Subadult        0        1     0
## 7    Adult        0        0     1
## 8    Adult        0        0     1
## 9    Adult        0        0     1</code></pre>
<p>When we create our general linear model to accommodate these multiple
groups, we now need to have an X for every one of these dummy-coded
columns. But, we are going to leave one out.</p>
<p><strong><span class="math inline">\(Y = \beta_0 + \beta_1 Subadult +
\beta_2 Adult + \epsilon \sim N(0, \sigma)\)</span></strong></p>
<p>You might be scratching your head why ‘Juvenile’ wasn’t included. We
don’t need to include it because it will be automatically be captured by
the <span class="math inline">\(\beta_0\)</span> intercept!</p>
<ul>
<li>Subadults will be captured by the <span
class="math inline">\(\beta_1 Subadult\)</span> term.</li>
<li>Adults will be captured by the <span class="math inline">\(\beta_2
Adult\)</span> term.</li>
<li>So then Juveniles will be all the individuals that weren’t in
Subadult or Adults categories and thus will captured by the intercept as
the ‘reference’ group.</li>
</ul>
<p>The reference group is the group by which all others are
compared.</p>
<p>Another way to look at this is to examine our dummy-coded columns. If
we look at the ‘Subadult’ and ‘Adult’ columns, we actually don’t need
the ‘Juvenile’ column to know which observations are of juveniles:</p>
<pre><code>##        Age Subadult Adult
## 1 Juvenile        0     0
## 2 Juvenile        0     0
## 3 Juvenile        0     0
## 4 Subadult        1     0
## 5 Subadult        1     0
## 6 Subadult        1     0
## 7    Adult        0     1
## 8    Adult        0     1
## 9    Adult        0     1</code></pre>
<p>The individuals that were 0 for both Subadults and Adults must be
Juveniles, by the process of elimination.</p>
<p><strong>Let’s see how this works mathematically:</strong></p>
<p><strong><span class="math inline">\(Y = \beta_0 + \beta_1 Subadult +
\beta_2 Adult + \epsilon\)</span></strong></p>
<p><strong><span class="math inline">\(Y(juv) = \beta_0 +
\cancel{\beta_1 * 0} + \cancel{\beta_2 * 0} +
\epsilon\)</span></strong></p>
<p><strong><span class="math inline">\(Y(juv) = \beta_0 +
\epsilon\)</span></strong></p>
<p>The meaning of <span class="math inline">\(\beta_0\)</span> has not
changed – the average Y (size) of our reference group.</p>
<p><strong><span class="math inline">\(Y(sub) = \beta_0 + \beta_1 * 1 +
\cancel{\beta_2 * 0} + \epsilon\)</span></strong></p>
<p><strong><span class="math inline">\(Y(sub) = \beta_0 + \beta_1 +
\epsilon\)</span></strong></p>
<p>The meaning of <span class="math inline">\(\beta_1\)</span> has not
changed either – the difference between juveniles and subadults.</p>
<p><strong><span class="math inline">\(Y(adult) = \beta_0 +
\cancel{\beta_1 * 0} + \beta_2 * 1 + \epsilon\)</span></strong></p>
<p><strong><span class="math inline">\(Y(adult) = \beta_0 + \beta_2 +
\epsilon\)</span></strong></p>
<p>Our new variable, <span class="math inline">\(\beta_2\)</span>, has a
similar meaning to <span class="math inline">\(\beta_1\)</span> – the
difference between adults and juveniles.</p>
<p>I like to visualize these things <strong>graphically</strong>. So I
am going to draw something that might help us visualize this on the
board:</p>
<p><img src="lecture_9_files/figure-html/stripplot-1.png" width="672" /></p>
<p>Note: our <strong>error</strong> is normally distributed with a mean
= 0, centered on the average, with a standard deviation of <span
class="math inline">\(\sigma\)</span>.</p>
<p>Or:</p>
<p><img src="lecture_9_files/figure-html/stripplot-2-1.png" width="672" /></p>
<p><strong>Q:</strong> Does anyone have any questions?</p>
<p>You might be wondering… how would we estimate the difference between
subadults and adults?</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> tells us about the
difference between juveniles and subadults, and whether it’s
statistically significant.</li>
<li><span class="math inline">\(\beta_2\)</span> tells us about the
difference between juveniles and adults, and whether it’s statistically
significant.</li>
<li>But neither tells us about the difference between juveniles and
adults.</li>
</ul>
<p><strong>Q:</strong> Anybody know how we might learn about the
difference between juveniles and adults? <strong>Changing the
reference.</strong></p>
<div id="comparison-of-multiple-groups-in-r" class="section level3">
<h3>Comparison of multiple groups in R</h3>
<p>Let’s see what this would look like in R. Download some simulated
data <a href="lecture_9_ages.csv">here</a>.</p>
<pre class="r"><code>### Code to test for differences among three groups

# Read in the data
datum &lt;- read.csv(&quot;lecture_9_ages.csv&quot;)

# Examine the data
head(datum)</code></pre>
<pre><code>##   X      Age      Size
## 1 1 Juvenile 103.89102
## 2 2 Juvenile  84.03008
## 3 3 Juvenile  75.82466
## 4 4 Juvenile  66.55006
## 5 5 Juvenile  33.93506
## 6 6 Juvenile  97.62674</code></pre>
<pre class="r"><code># Plot
stripchart(Size ~ Age, data = datum, vertical = TRUE, method = &quot;jitter&quot;,
           pch = 19, xlab = &quot;Age&quot;, ylab = &quot;Body size (cm)&quot;)</code></pre>
<p><img src="lecture_9_files/figure-html/three-groups-analysis-1.png" width="672" /></p>
<pre class="r"><code># Re-order categorical X-data
datum$Age &lt;- factor(datum$Age, levels = c(&quot;Juvenile&quot;, &quot;Subadult&quot;, &quot;Adult&quot;))

# Plot
stripchart(Size ~ Age, data = datum, vertical = TRUE, method = &quot;jitter&quot;,
           pch = 19, xlab = &quot;Age&quot;, ylab = &quot;Body size (cm)&quot;)</code></pre>
<p><img src="lecture_9_files/figure-html/three-groups-analysis-2.png" width="672" /></p>
<pre class="r"><code># Add in dummy-coding
dummy &lt;- model.matrix(~ Age -1, data = datum)
colnames(dummy) &lt;- c(&quot;Juvenile&quot;, &quot;Subadult&quot;, &quot;Adult&quot;) # rename columns
# be careful; make sure name order reflects order of categorical variable &#39;Age&#39;
datum &lt;- cbind(datum, dummy) # bind to dataframe

# Re-examine data
head(datum)</code></pre>
<pre><code>##   X      Age      Size Juvenile Subadult Adult
## 1 1 Juvenile 103.89102        1        0     0
## 2 2 Juvenile  84.03008        1        0     0
## 3 3 Juvenile  75.82466        1        0     0
## 4 4 Juvenile  66.55006        1        0     0
## 5 5 Juvenile  33.93506        1        0     0
## 6 6 Juvenile  97.62674        1        0     0</code></pre>
<p>‘Truth’ for these data are:</p>
<ul>
<li>Juveniles: 75 kg, so <span class="math inline">\(\beta_0\)</span> =
75 kg</li>
<li>Subadults: 200 kg, so <span class="math inline">\(\beta_1\)</span> =
125 kg</li>
<li>Adults: 250 kg, so <span class="math inline">\(\beta_2\)</span> =
175 kg</li>
</ul>
<p>Let’s use ‘lm()’ to test for these differences in R:</p>
<pre class="r"><code>## Analysis of variance; &#39;aov()&#39;
help(aov)
# Fit an analysis of variance... by calling &#39;lm()&#39;!!

# Run an ANOVA
results &lt;- aov(Size ~ Age, data = datum)
summary(results)</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Age          2 339600  169800   362.5 &lt;2e-16 ***
## Residuals   57  26697     468                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>What does it give us…? An ANOVA table!</p>
<p><strong>Q:</strong> What’s missing here..? Estimates of effects – and
whether those individual effects are significant or not. So, this is
<strong>not very useful</strong>.</p>
<pre class="r"><code>## Multiple comparison using &#39;lm()&#39;
# Run analysis
results2 &lt;- lm(Size ~ Age, data = datum)
summary(results2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Age, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.662 -16.076  -1.663  13.746  60.643 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   70.597      4.839   14.59   &lt;2e-16 ***
## AgeSubadult  133.581      6.844   19.52   &lt;2e-16 ***
## AgeAdult     176.732      6.844   25.82   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.64 on 57 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9246 
## F-statistic: 362.5 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Here are the results, and by now hopefully this is starting to look
familiar!</p>
<p><strong>Q:</strong> What is the reference group? How do we know?</p>
<ul>
<li>The intercept is our estimate of mean size of juveniles.</li>
<li>‘AgeSubadult’ is the effect of being subadult compared to
juveniles.</li>
<li>‘AgeAdult’ is the effect of being an adult compared to
juveniles.</li>
</ul>
<p>Notice: these estimates are pretty good estimates of truth! Which is
what statistics should do. It’s not perfect because there’s randomness
in our data (process error, sampling error, etc.).</p>
<p>And then all of our usual metrics at the bottom.</p>
</div>
<div id="difference-between-anova-and-t-test" class="section level3">
<h3>Difference between ANOVA and t-test</h3>
<p>Let’s review the difference between ANOVA and t-test. We just did an
ANOVA, but we could have done a bunch of t-tests. Why not just do a
bunch of t-tests to do all of these individual comparisons? Why might I
not want to do that?</p>
<p><strong>Q:</strong> Can anyone remember why we might not want to a
bunch of t-tests? Inflating our risk of committing Type I error!</p>
<p>Remember: Type I error is when we reject the null when in fact it is
True; what we <strong>most want to avoid</strong>. We want to keep our
risk of committing Type I error to be no greater than 0.05.</p>
<ul>
<li>When we calculate a single p-value, we have a 5% chance (0.05) of
getting things wrong.</li>
<li>When we do more and more tests, we increase the chance of committing
Type I error.</li>
</ul>
<p><strong>If we did 3 t-tests</strong>:</p>
<ul>
<li><strong>P(Not committing error) = (1 - <span
class="math inline">\(\alpha\)</span>)</strong> – we take this to the
power of the number of tests we will do</li>
<li><strong>P(No errors) = (1 - 0.05)^3</strong></li>
<li><strong>P(&gt;1 errors) = 1 - (1 - 0.05)^3</strong></li>
</ul>
<pre class="r"><code># Probability of committing no errors in three t-tests
(1 - 0.05)^3</code></pre>
<pre><code>## [1] 0.857375</code></pre>
<pre class="r"><code># Probability of committing &gt;=1 Type I errors in three t-tests
1 - (1 - 0.05)^3</code></pre>
<pre><code>## [1] 0.142625</code></pre>
<p>This is why they teach us to use analyses like ANOVA in statistics.
It is meant to be one single test that can evaluate multiple comparisons
and thus minimizes our risk of committing Type I error.</p>
<ul>
<li><p>Concept: first, run ANOVA, and get a single p-value. That p-value
tells you whether <strong>at least two groups are different from another
group</strong>; but it does not mean that all groups are
different.</p></li>
<li><p><strong>ANOVA w/ p &lt; 0.05 – at least 2 groups are
different</strong></p></li>
<li><p>After getting the significant p-value, you then do a
<strong>‘post-hoc’ test</strong> to evaluate those differences. (We’ll
talk about this in a few days.)</p></li>
</ul>
<p>The important part is that our ‘lm()’ summary output gives us the
single ANOVA p-value, which is at the bottom of the summary.</p>
<p>Another way to get this is to use:</p>
<pre class="r"><code># ANOVA test
anova(results2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Size
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Age        2 339600  169800  362.54 &lt; 2.2e-16 ***
## Residuals 57  26697     468                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>So now we know that there is at least two groups are differnet than
eachother.</p>
<p>To know <strong>which ones</strong>, we can use a ‘post-hoc test’… or
we can just look up to the results of the linear model! The p-values
with our effects tell us that:</p>
<ul>
<li>Subadults are significantly larger than juveniles</li>
<li>Adults are also significantly larger than juveniles</li>
</ul>
<p>And now we also have <strong>estimates</strong>! The effect sizes for
each of the <span class="math inline">\(\beta\)</span> values. We get
all of this information from a single annalysis and a single model
output.</p>
</div>
<div id="reporting-results" class="section level3">
<h3>Reporting results</h3>
<p>How do we report the results?</p>
<pre class="r"><code>summary(results2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Age, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.662 -16.076  -1.663  13.746  60.643 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   70.597      4.839   14.59   &lt;2e-16 ***
## AgeSubadult  133.581      6.844   19.52   &lt;2e-16 ***
## AgeAdult     176.732      6.844   25.82   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.64 on 57 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9246 
## F-statistic: 362.5 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>confint(results2)</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept)  60.90658  80.28737
## AgeSubadult 119.87685 147.28543
## AgeAdult    163.02758 190.43616</code></pre>
<p>“We found that subadults were 133.6 kg (+/-13.7; +/-95% CI) heavier
than juveniles (p &lt; 2e-16).”</p>
<p>“We found that adults were 176.7 kg (+/-13.7; +/-95% CI) heavier than
juveniles (p &lt; 2e-16).”</p>
<p>But, there are three groups, so we will need to write three sentences
to report all of those comparisons. To do this, we have to recreate our
results object. It’s pretty easy!</p>
<p>We will use the ‘relevel()’ function</p>
<pre class="r"><code># Re-run analysis with different reference
results3 &lt;- lm(Size ~ relevel(Age, ref = &quot;Subadult&quot;), data = datum)
summary(results3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ relevel(Age, ref = &quot;Subadult&quot;), data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.662 -16.076  -1.663  13.746  60.643 
## 
## Coefficients:
##                                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                             204.178      4.839  42.192  &lt; 2e-16 ***
## relevel(Age, ref = &quot;Subadult&quot;)Juvenile -133.581      6.844 -19.519  &lt; 2e-16 ***
## relevel(Age, ref = &quot;Subadult&quot;)Adult      43.151      6.844   6.305 4.53e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.64 on 57 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9246 
## F-statistic: 362.5 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This new summary looks a little uglier… but it gives us the
information that we needed.</p>
<p>“We found that adults were 43.2 kg (+/-13.7; +/-95% CI) heavier than
subadults (p = 4.53e-08).”</p>
<p>Note: the juvenile-subadult estimate remained the same, but became
negative.</p>
<p><strong>Questions?</strong></p>
<p>I am going to encourage us to build models that can evaluate global
difference and within-group differences within one single model, such as
we have done using ‘lm()’, <strong>for two reasons</strong>.</p>
<ul>
<li>First, this is more simple and minimize extra steps of having to do
‘post-hoc tests’. As we get more advanced with our approaches, post-hoc
tests will not exist for all of your needs, so building models that can
test for differences within the model is the best approach, in my
opinion.</li>
<li>Second, do we really care about p-values? Post-hoc tests are used to
generate p-values, but we don’t think p-values are the goal of
statistics. We want to measure effects, and the modeling approach we are
using here is good at estimating effects.</li>
</ul>
</div>
<div id="using-the-dummy-coded-variables" class="section level3">
<h3>Using the dummy-coded variables</h3>
<p>Dummy coded variables can be pretty useful!</p>
<ul>
<li>You can combine different dummy-coded variables</li>
<li>And you can avoid the ugly ‘relevel()’ results</li>
<li>It may be more intuitive</li>
</ul>
<p>Turns out we can really easily fit these models using the
‘dummy-coded’ variables. Here’s how that works.</p>
<pre class="r"><code># Using the dummy-coded variables to run this analysis
results4 &lt;- lm(Size ~ Subadult + Adult, data = datum)
summary(results4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Subadult + Adult, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.662 -16.076  -1.663  13.746  60.643 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   70.597      4.839   14.59   &lt;2e-16 ***
## Subadult     133.581      6.844   19.52   &lt;2e-16 ***
## Adult        176.732      6.844   25.82   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.64 on 57 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9246 
## F-statistic: 362.5 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code># Changing the reference
results5 &lt;- lm(Size ~ Juvenile + Adult, data = datum)
summary(results5)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Juvenile + Adult, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.662 -16.076  -1.663  13.746  60.643 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  204.178      4.839  42.192  &lt; 2e-16 ***
## Juvenile    -133.581      6.844 -19.519  &lt; 2e-16 ***
## Adult         43.151      6.844   6.305 4.53e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.64 on 57 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9246 
## F-statistic: 362.5 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We purposefully left-out ‘Juvenile’, and it is forced to the
reference.</p>
<p>These results are the same as when we fit the model using the ‘Age’
categorical variable.</p>
<p>I like these results better because the effect description is really
accurate: “Effect of being subadult” is more intuitive than the “Effect
of being”AgeSubadult”, in my opinion.</p>
<p>What if we specified all three of the dummy-coded variables, would
that screw it up?</p>
<pre class="r"><code># Using the dummy-coded variables to run this analysis
results6 &lt;- lm(Size ~ Subadult + Adult + Juvenile, data = datum)
summary(results6)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Subadult + Adult + Juvenile, data = datum)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.662 -16.076  -1.663  13.746  60.643 
## 
## Coefficients: (1 not defined because of singularities)
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   70.597      4.839   14.59   &lt;2e-16 ***
## Subadult     133.581      6.844   19.52   &lt;2e-16 ***
## Adult        176.732      6.844   25.82   &lt;2e-16 ***
## Juvenile          NA         NA      NA       NA    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 21.64 on 57 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9246 
## F-statistic: 362.5 on 2 and 57 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Juvenile was forced to be “NA”, and instead Juvenile was forced to be
reference because – it was the last one included.</p>
<p>Let’s try a little critical thinking exercise. Consider this
model:</p>
<pre class="r"><code># Using the dummy-coded variables to run this analysis
results7 &lt;- lm(Size ~ Adult, data = datum)
summary(results7)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ Adult, data = datum)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -103.452  -47.779   -2.938   54.487  127.433 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  137.388      9.403   14.61  &lt; 2e-16 ***
## Adult        109.941     16.287    6.75 7.69e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 59.47 on 58 degrees of freedom
## Multiple R-squared:   0.44,  Adjusted R-squared:  0.4303 
## F-statistic: 45.57 on 1 and 58 DF,  p-value: 7.689e-09</code></pre>
<p><strong>Q:</strong> What does this model do…?</p>
<p>It compares the size of adults compared to the size of all other
observations combined into a single group. Juveniles and subadults are
lumped.</p>
<p>“We found that adults were 109.9 kg (…) heavier than juveniles and
subadults combined as a group (p = 7.69e-09).”</p>
<p>Here’s another way to do it:</p>
<pre class="r"><code># Using the dummy-coded variables to run this analysis
results8 &lt;- lm(Size ~ I(Juvenile + Subadult), data = datum)
# I() is a function to do whatever is inside the parentheses
summary(results8)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Size ~ I(Juvenile + Subadult), data = datum)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -103.452  -47.779   -2.938   54.487  127.433 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              247.33      13.30   18.60  &lt; 2e-16 ***
## I(Juvenile + Subadult)  -109.94      16.29   -6.75 7.69e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 59.47 on 58 degrees of freedom
## Multiple R-squared:   0.44,  Adjusted R-squared:  0.4303 
## F-statistic: 45.57 on 1 and 58 DF,  p-value: 7.689e-09</code></pre>
<p>These are advantages of using ‘dummy-coded’ variables! It gives us
<em>flexibility.</em></p>
<p><strong>Questions?</strong></p>
</div>
</div>
<div id="summary-1" class="section level2">
<h2>Summary</h2>
<ul>
<li><p>It doesn’t matter how many groups your categorical variable has.
It’s still ‘lm(Y ~ X)’.</p></li>
<li><p>It will create a number of effects (<span
class="math inline">\(\beta\)</span>). The number of <span
class="math inline">\(\beta\)</span>s will be the number of groups,
<span class="math inline">\(n\)</span>, minus 1 (the
reference).</p></li>
<li><p>We have a different results sentence now, that we will use for
any categorical variables.</p></li>
<li><p>For categorical variables, you will need a sentence for all
pairwise comparisons.</p></li>
</ul>
<p><br></p>
</div>
<div id="truth" class="section level2">
<h2>Truth</h2>
<p>Code to simulate the three-age data and save it. Just here in case
you are interested in how it was made.</p>
<pre class="r"><code>### Code for simulating data to be analyzed body size data for two sexes

# Simulate the binomial X-variable (sex)
n &lt;- 60
x &lt;- c(rep(&quot;Juvenile&quot;, n/3), rep(&quot;Subadult&quot;, n/3), rep(&quot;Adult&quot;, n/3))
x &lt;- factor(x, levels = c(&quot;Juvenile&quot;, &quot;Subadult&quot;, &quot;Adult&quot;))

# Simulate continuous y-variable data
y &lt;- ifelse(x == &quot;Juvenile&quot;, rnorm(n/3, mean = 75, sd = 20), #juveniles
            ifelse(x == &quot;Subadult&quot;, rnorm(n/3, mean = 200, sd = 20), #subad
              rnorm(n/2, mean = 250, sd = 20))) #adults

# Create dataframe
datum &lt;- data.frame(Age = x, Size = y)

# Save these data for future use
write.csv(datum, &quot;lecture_9_ages.csv&quot;)</code></pre>
<p><a href="lecture_10.html">–go to next lecture–</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
